---
- name: "Create {{ heco_user_name }} user"
  user:
    name: "{{ heco_user_name }}"
    home: "/home/{{ heco_user_name }}"
    shell: /bin/bash
    system: yes

- name: "Creates directory"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ heco_user_name }}"
    group: "{{ heco_user_name }}"
    mode: 0755
    recurse: yes
  loop:
    - "{{ heco_root }}"
    - "{{ heco_data }}"
    - "{{ heco_service_dir }}"
    - "{{ heco_data }}/logs"

- name: "Enable linger for {{ heco_user_name }}"
  command: "loginctl enable-linger {{ heco_user_name }}"

- name: "Download source code hecochain"
  ansible.builtin.git:
    repo: "{{ heco_repo }}"
    dest: "{{ heco_root }}"
    force: yes

- name: "Compile geth"
  make:
    chdir: "{{ heco_root }}/huobi-eco-chain"
    target: geth

- name: "Change permissions for geth"
  ansible.builtin.file:
    path: "{{ heco_geth_path }}"
    owner: "{{ heco_user_name }}"
    group: "{{ heco_user_name }}"
    mode: 0755

- name: "Create config.toml"
  template:
    src: "config.toml.j2"
    dest: "{{ heco_config }}"
    owner: "{{ heco_user_name }}"
    group: "{{ heco_user_name }}"
    mode: 0400
